title: Sarah Shenouda
author: Sarah Shenouda
email: sshenouda@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"

# social links
instagram_username: sarah_shenouda # DO NOT include the @ character, or else the build will fail!
github_username:  sshenouda # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
